---
deployment:
  tasks:
    - export DEPLOYPATH="/home/r0pbgirhttli/public_html"
    - export REPO="https://github.com/sw-carlos-cristobal/ccristobal-dev.git"
    - export BRANCH="main"
    - /bin/rm -rf ${DEPLOYPATH}
    - /bin/mkdir ${DEPLOYPATH}
    - git clone ${REPO} ${DEPLOYPATH}
    - cd ${DEPLOYPATH}
    - git checkout ${BRANCH}
    - yarn install --production
    - yarn build
